name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3

     - name: Build docker image
       run: docker build -t python_app . 

     - name: upload artifacts
       uses: actions/upload-artifact@v3
       with:
         name: docker_python_artifacts
         path: dist
