name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout main branch
       uses: actions/checkout@v2

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1

     - name: Set up Docker Buildx 
       uses: docker/setup-buildx-action@v1
      
     - name: Login to JFrog 
       uses: docker/login-action@v1
       with:
          registry: https://superclient.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}
      
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: superclient.jfrog.io/pythonapp:latest