name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3

     - name: Build docker image
       run: docker build -t python_app . 

     - name: upload docker image artifacts
       uses: ishworkh/docker-image-artifact-upload@v1
       with:
         image: "python_app:latest" 
