name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3

     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v2

     - name: Build Docker images
       uses: docker/build-push-action@v3 
       with:
         tags: python_app

     - name: login to jfrog
       uses: docker/login-action@v1
       with:
         registry: superclient.jfrog.io/artifactory/docker-trial/
         username: ${{ secrets.JF_USER }}
         password: ${{ secrets.JF_PASSWORD }}

     - name: Deploy to jfrog 
       run: |
         jf docker tag 10 superclient.jfrog.io/docker-trial/docker-trial/python_app:10
         jf docker push superclient.jfrog.io/artifactory/docker-trial/python_app:10

    #  - name: Build docker image
    #    run: docker build -t python_app:latest . 

    #  - name: upload docker image artifacts
    #    uses: ishworkh/docker-image-artifact-upload@v1
    #    with:
    #      image: "python_app:latest" 
    #     #  name: docker_python_artifacts
    #     #  path: dist

    #  - name: Download artifacts
    #    uses: ishworkh/docker-image-artifact-download@v1
    #    with:
    #     image: "python_app:latest"

    #  - name: push to artifactory
    #    uses: jfrog/setup-jfrog-cli@v3
    #    env:
    #       JF_URL: https://superclient.jfrog.io/artifactory/docker-trial/
    #       JF_USER: ${{ secrets.JF_USER }}
    #       JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
    #  - name: Deploy to jfrog 
    #    run: |
    #       jf docker push https://superclient.jfrog.io/artifactory/docker-trial/ \
    #       --build-name=docker-1 \
    #       --build-number=1

      # - run: |
      #    jfrog rt u ./action_image_artifact_python_app_latest.zip artifactory-build-info/ 
      #    jf rt bp



  