name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout main branch
       uses: actions/checkout@v2

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1

     - name: Set up Docker Buildx 
       uses: docker/setup-buildx-action@v1
      
     - name: Build and push to artifactory
       uses: jfrog/setup-jfrog-cli@v3
       env:
          JF_URL: https://superclient.jfrog.io/
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
     - run: |
         jfrog rt docker-push python_app/latest docker
         jf rt bp


  