name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3

    #  - name: Setup JFrog CLI
    #    uses: jfrog/setup-jfrog-cli@v2

     - name: Set up QEMU 
       uses: docker/setup-qemu-action@v1
      
     - name: Set up Docker Buildx 
       uses: docker/setup-buildx-action@v1

    #  - name: Build Docker images
    #    uses: docker/build-push-action@v3 
    #   #  with:
    #   #   #  tags: ff9697bb6132

     - name: login to jfrog
       uses: docker/login-action@v1
       with:
         registry: superclient.jfrog.io
         username: ${{ secrets.JF_USER }}
         password: ${{ secrets.JF_PASSWORD }}
     
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: superclient.jfrog.io/artifactory/docker-trial/python_app:latest


    #  - name: Deploy to jfrog 
    #    run: |
    #      jf docker tag ff9697bb6132 superclient.jfrog.io/docker-trial/docker-trial/python_app:latest
    #      jf docker push superclient.jfrog.io/artifactory/docker-trial/python_app:latest

    #  - name: Build docker image
    #    run: docker build -t python_app:latest . 

    #  - name: upload docker image artifacts
    #    uses: ishworkh/docker-image-artifact-upload@v1
    #    with:
    #      image: "python_app:latest" 
    #     #  name: docker_python_artifacts
    #     #  path: dist

    #  - name: Download artifacts
    #    uses: ishworkh/docker-image-artifact-download@v1
    #    with:
    #     image: "python_app:latest"

    #  - name: push to artifactory
    #    uses: jfrog/setup-jfrog-cli@v3
    #    env:
    #       JF_URL: https://superclient.jfrog.io/artifactory/docker-trial/
    #       JF_USER: ${{ secrets.JF_USER }}
    #       JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
    #  - name: Deploy to jfrog 
    #    run: |
    #       jf docker push https://superclient.jfrog.io/artifactory/docker-trial/ \
    #       --build-name=docker-1 \
    #       --build-number=1

      # - run: |
      #    jfrog rt u ./action_image_artifact_python_app_latest.zip artifactory-build-info/ 
      #    jf rt bp



  