name: build and push to jfrog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3

     - name: Build docker image
       run: docker build -t python_app . 

     - name: upload docker image artifacts
       uses: ishworkh/docker-image-artifact-upload@v1
       with:
         image: "latest" 
        #  name: docker_python_artifacts
        #  path: dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifacts@v3
  #       with:
  #         name: docker_python
  #         path: dist 

  #     - name: push to artifactory
  #       uses: jfrog/setup-jfrog-cli@v3
  #       env:
  #         JF_URL: https://superclient.jfrog.io/
  #         JF_USER: ${{ secrets.JF_USER }}
  #         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
  #     - run: |
  #        jfrog rt u python_app artifactory-build-info/ 
  #        jf rt bp


  